### ISSUE TITLE
Maven release in pom file

### ISSUE THREAD

**Issue by TrungMa1** [Lucia560/Jakarta_labb#12]
Should we also add maven release like Martin said?
<maven.compiler.release>20</maven.compiler.release>

And is this something we would delete or keep in?
<maven.compiler.target>21</maven.compiler.target>
<maven.compiler.source>21</maven.compiler.source>

**Comment by Lucia560** [comment]
I think compile.release replaces the other 2(.target  and .source) . When I made the pom file it did not work with compile.release  and I did not try more. You can try it locally, if it works then is perfectly fine but is not mandatory:)

**Comment by marcusju23** [comment]
> Should we also add maven release like Martin said? <maven.compiler.release>20</maven.compiler.release>
> 
> And is this something we would delete or keep in? <maven.compiler.target>21</maven.compiler.target> <maven.compiler.source>21</maven.compiler.source>

I believe @BarbieQkiller already addressed this in #6

**Comment by TrungMa1** [comment]
Ye sorry, didnt have the latest merged PR. I can see it have been changed
