### ISSUE TITLE
Create a @Enitity movie class

### ISSUE THREAD

**Issue by TrungMa1** [Lucia560/Jakarta_labb#13]
We should add some attributes to a created Movie class like (Title, Genre, ReleaseYear, Duration, Rating) maybe?

Steps:
Create the @Entity Movie class.
Define the attributes with the correct data types.
Implement getter and setter methods for all attributes.

**Comment by Lucia560** [comment]
Yes. As I saw in Martins code he has every class in package, DTO, entities etc. So a package with this class in ?
