### ISSUE TITLE
Switch to WORKDIR from CD in Dockerfile

### ISSUE THREAD

**Issue by marcusju23** [Lucia560/Jakarta_labb#33]
Update the Dockerfile to use the **WORKDIR** instruction instead of the **CD** command. The **WORKDIR** instruction sets the working directory for subsequent instructions, making the Dockerfile more readable and reducing the risk of errors. [Read more here](https://docs.docker.com/develop/develop-images/instructions/#workdir).

**Comment by BarbieQkiller** [comment]
I absolutely love lists and things so I give this approach big thumbs up 😁
