### ISSUE TITLE
Make application runnable

### ISSUE THREAD

**Issue by BarbieQkiller** [Lucia560/Jakarta_labb#40]
It is of utmost importance that the application is runnable atm it is not. Am on it since a few hours back, lots and lots to do to fix it. Stay tuned 😀

**Comment by BarbieQkiller** [comment]
> Yes, we need to deal with this important issue as soon as possible.

I am dealing with it right now 😁

**Comment by marcusju23** [comment]
@BarbieQkiller Just a question, I am working on validations #37 and im doing tests. Is this error related to this issue you reckon, im a tiny bit confused? 🤔 

`feb. 28, 2024 6:43:10 EM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 8.0.1.Final
feb. 28, 2024 6:43:10 EM jakarta.persistence.spi.PersistenceProviderResolverHolder$DefaultPersistenceProviderResolver log
WARNING: jakarta.persistence.spi::No valid providers found.`

**Comment by BarbieQkiller** [comment]
> @BarbieQkiller Just a question, I am working on validations #37 and im doing tests. Is this error related to this issue you reckon? Im a tiny bit confused.. 🤔
> 
> `feb. 28, 2024 6:43:10 EM org.hibernate.validator.internal.util.Version <clinit> INFO: HV000001: Hibernate Validator 8.0.1.Final feb. 28, 2024 6:43:10 EM jakarta.persistence.spi.PersistenceProviderResolverHolder$DefaultPersistenceProviderResolver log WARNING: jakarta.persistence.spi::No valid providers found.`

Luckily no. ☺️

**Comment by BarbieQkiller** [comment]
> @BarbieQkiller Just a question, I am working on validations #37 and im doing tests. Is this error related to this issue you reckon? Im a tiny bit confused.. 🤔
> 
> `feb. 28, 2024 6:43:10 EM org.hibernate.validator.internal.util.Version <clinit> INFO: HV000001: Hibernate Validator 8.0.1.Final feb. 28, 2024 6:43:10 EM jakarta.persistence.spi.PersistenceProviderResolverHolder$DefaultPersistenceProviderResolver log WARNING: jakarta.persistence.spi::No valid providers found.`

If you are writing tests for endpoints are you touching any of the repository code? That might be one thing, another could be the scope in the pom.xml. The scope should be changed to provided. ☺️

**Comment by marcusju23** [comment]
There are no endpoint tests, only tests to verify if validations are working. Thank you for the quick responses and commitments!

**Comment by BarbieQkiller** [comment]
> There are no endpoint tests, only tests to verify if validations are working. Thank you for the quick responses and commitments!

My reply disappeared, so here is the short version. What do you think about making dto's where we need them to facilitate unit testing, since we need them anyways. This might make your job a lot easier ☺️
