### ISSUE TITLE
Very minor if-statement

### ISSUE THREAD

**Issue by TrungMa1** [Lucia560/Jakarta_labb#58]
Putting a if-statement in the updateMovie method in our MovieResource class is not strictly necessary, but it's recommended for ensuring robustness and data integrity. Without the if statement, if the movie with the specified ID doesn't exist, the movie object will be null, and attempting to update it could lead to unexpected behavior or errors.

What do you guys think? Very minor detail.

**Comment by TrungMa1** [comment]
i could just add a simple if statement if you guys approve it

**Comment by BarbieQkiller** [comment]
I am moving around in that class as I mentioned yesterday but you are very welcome to make that change, good suggestion ☺️

**Comment by TrungMa1** [comment]
@BarbieQkiller if you're already working on that class, i'll let you do your thing! :)

**Comment by BarbieQkiller** [comment]
> @BarbieQkiller if you're already working on that class, i'll let you do your thing! :)

Thank you! I am but I just wanted to say that your suggestion is a really great one. Well done!

**Comment by TrungMa1** [comment]
Thank you and thank you for quick response.
