### ISSUE TITLE
Add PostgreSQL JDBC Driver as Maven Dependency

### ISSUE THREAD

**Issue by marcusju23** [Lucia560/Jakarta_labb#65]
Adding the PostgreSQL JDBC driver as a Maven dependency aligns with best practices and will contribute to making our project more efficient and easier to maintain. This step ensures that we follow established standards for dependency management, promoting consistency and enhancing overall project robustness.

**Comment by marcusju23** [comment]
I'm holding off on submitting the pull request because I'm a bit confused. Is PostgreSQL downloaded within the Docker image?

**Comment by Lucia560** [comment]
I tried to use the docker but it did not work for me. I still have to add the dependency or the driver + datasource in the standalone- full.xml. I am not sure if I did something wrong

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Lucia560** [comment]
![image](https://github.com/Lucia560/Jakarta_labb/assets/143084551/760523a2-141a-4a73-bcf9-6112d46f0a15)
This is my error  if I use the commands in READ.me
