### ISSUE TITLE
Add SonarCloud

### ISSUE THREAD

**Issue by marcusju23** [Lucia560/Jakarta_labb#7]
Would it be beneficial to integrate SonarCloud for enhanced code coverage? If the decision is affirmative, it's essential to incorporate the jacoco-maven-plugin and invoke SonarLint using a key from our build pipeline to ensure effective test coverage.

**Comment by TrungMa1** [comment]
Integrating SonarCloud into our project would be great for improving code quality, identifying bugs and enhancing overall code coverage.

**Comment by Lucia560** [comment]
Good point. I will try to fix this today :)

**Comment by TrungMa1** [comment]
This issue is done,right?

**Comment by Lucia560** [comment]
No is not done yet .

**Comment by marcusju23** [comment]
> This issue is done,right?

There are no issue/PR referring to it as closed. Please be mindful of that in the future before closing to prevent any confusion. 👍
