### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by marcusju23** [Lucia560/Jakarta_labb#8]
Given that multiple individuals are contributing to this project, it's possible that diverse personal formatting preferences could lead to issues. This is particularly problematic when several team members are updating files, as changes may occur solely due to variations in formatting rules.

To address this concern, we can implement a solution by creating an .editorconfig file. This file would contain standardized settings that are universally applicable. Once incorporated into the project, these settings will automatically take effect across all Integrated Development Environments (IDEs) that support the .editorconfig format, ensuring consistent formatting and minimizing discrepancies caused by individual preferences. Would this suffice? 🤔 [Google Java CodeStyle editorconfig](https://gist.github.com/patrick-werner/1a752c624e96cd1a7c1527c5b1936970)

**Comment by TrungMa1** [comment]
do we want this setting?
#Unix-style Line Endings:

end_of_line = lf
Example1: This is line 1\n

or do we want:
Example2: This is line 1\r\n

**Comment by TrungMa1** [comment]
warning: in the working copy of '.idea/misc.xml', LF will be replaced by CRLF the next time Git touches it

Maybe i should keep *end_of_line = lf* in the .editorconfig file.
